### ISSUE TITLE
Only issues "Off" commands

### ISSUE THREAD

**Issue by aracdin** [SCCMOG/Home-Assistant#3]
Many thanks for this! As I have an energy meter, couple of relays and a thermostat I'd be interested in any extensions. I'll have a go myself and provide code, once I've learnt python...
I currently have an odd problem, I can only issue "Off" commands. If I run LightwaveRF_service.py from the command line, I see nothing when I turn a light (simple on/off through a Lightwave power socket) on - but see off commands. If I turn the light on with the lightwave app, I can see the command turns it off OK. I noticed that if I open an individual light, it features a dimmer - is there a parameter to force it to simple on/off device?

**Comment by aracdin** [comment]
OK... I go and eat and come back, change nothing and now when I drag a light dimmer I see:
[x] Sent: 666, !R1D1FdP32|Lights 32|Hearts to LightwaveRF Link: [Link IP Address]
... including on the lights that I didn't move the dimmer on. Since these are simple sockets, they don't respond to the dimmer command :-( Still no idea why I didn't originally see the FdP32 commands - do the dimmers default to 0 power so ignore the "on" command?

**Comment by aracdin** [comment]
So.. in lightwaverf_light.py "turn on", I put
	    msg = '%s|666, !%sF1|Turn On|%s ' % (self._rflink, self._deviceid, self._name)
instead of           
msg = '%s|666, !%sFdP32|Turn On|%s ' % (self._rflink, self._deviceid, self._name)
in the "else" clause (and discovering that python is touchy about tabs vs spaces..), my lights now come on :-). But dimmer units don't seem to recognise F1 as the same as FdP32, so this can't be a global fix so handle sockets.

**Comment by SCCMOG** [comment]
Copy my component and then create one for switches :) then we can use the light component for lights and your one for switches :)

**Comment by SCCMOG** [comment]
So rename it, place it into a switches folder and go for it buddy!

**Comment by aracdin** [comment]
So.. in lightwaverf_light.py "turn on", I put
	    msg = '%s|666, !%sF1|Turn On|%s ' % (self._rflink, self._deviceid, self._name)
instead of           
msg = '%s|666, !%sFdP32|Turn On|%s ' % (self._rflink, self._deviceid, self._name)
in the "else" clause (and discovering that python is touchy about tabs vs spaces..), my lights now come on :-). But dimmer units don't seem to recognise F1 as the same as FdP32, so this can't be a global fix so handle sockets.

**Comment by aracdin** [comment]
Thanks for the reply. As my lights are now working with the above hack and I don't have any dimmable lights wired in I think I'll take the time to understand how your LightwaveRF code works - I hate being ignorant :-) Thanks for the great work... Imay have more questions later ;-)
