### ISSUE TITLE
How to have dimming control in the UI

### ISSUE THREAD

**Issue by RevillWeb** [SCCMOG/Home-Assistant#4]
Hi, me again.

In your README you have simple switches for the lights and I've seen in the code for this component that it supports brightness. How can I change the control so I can alter the brightness from within Hass?

Thank you.

**Comment by SCCMOG** [comment]
It already works in Hass. Just click the light and you get a sliding bar :) there is simple switches and brightness controls. Open the python script :) 
[Brightness Support](https://github.com/SCCMOG/Home-Assistant/blob/master/LightwaveRF%20Light%20Custom%20Component/brightnessbar.JPG)

**Comment by SCCMOG** [comment]
Also works well with Alexa or google home when enabling either emulated hue, or the new skills for Alexa and google home :)

**Comment by RevillWeb** [comment]
Sorry, I totally missed that. Thank you!
